# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-predictorthologs-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.7.3
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  # TODO nf-core: Add required software dependencies here
  - bioconda::bedtools=2.29.2
  - bioconda::fastqc=0.11.8
  - bioconda::multiqc=1.7
  - conda-forge::r-markdown=1.1
  - conda-forge::r-base=3.6.1
  - bioconda::samtools=1.10
  - bioconda::diamond=0.9.30
  - bioconda::fastp=0.20.0
  - bioconda::bedtools=2.29.2
  - pip=20.0.2
  - conda-forge::rust=1.41.0
  - conda-forge::scikit-learn=0.22.1
  - conda-forge::pandas=1.0.3
  - conda-forge::tqdm=4.45.0
  - thombashi::pathvalidate=2.2.0
  - pip:
    - git+https://github.com/czbiohub/kh-tools.git@master#egg=khtools
    - git+https://github.com/czbiohub/sourmash.git@olgabot/hash2kmer-protein
