name: czbiohub-predictorthologs
channels:
  - file://apps/conda-BioHPDA
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.12
  - attrs=19.3.0
  - babel=2.8.0
  - backcall=0.2.0
  - bedtools=2.26.0
  - binutils_impl_linux-ppc64le=2.34
  - binutils_linux-ppc64le=2.34
  - bioawk=1.0
  - bioconductor-edger=3.28.0
  - bioconductor-limma=3.42.0
  - bleach=3.1.5
  - boost-cpp=1.70.0
  - boto3=1.14.20
  - botocore=1.17.20
  - brotlipy=0.7.0
  - bz2file=0.98
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - coloredlogs=10.0
  - colormath=3.0.0
  - cryptography=2.9.2
  - csvtk=0.20.0
  - curl=7.71.1
  - cycler=0.10.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - deprecation=2.1.0
  - diamond=0.9.35
  - dill=0.3.2
  - docutils=0.15.2
  - entrypoints=0.3
  - fastp=0.20.0
  - fastqc=0.11.9
  - freetype=2.10.2
  - fsspec=0.7.4
  - future=0.18.2
  - gcc_impl_linux-ppc64le=8.4.0
  - gcc_linux-ppc64le=8.4.0
  - gmp=6.2.0
  - htslib=1.10.2
  - icu=58.2
  - idna=2.10
  - ijson=2.4
  - imagesize=1.2.0
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - infernal=1.1.2
  - ipykernel=5.3.2
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.1
  - jinja2=2.11.2
  - jmespath=0.10.0
  - joblib=0.16.0
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.5
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - khmer=3.0.0a3
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - ld_impl_linux-ppc64le=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libdeflate=1.2
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc-ng=8.4.0
  - libgfortran-ng=8.4.0
  - libgomp=8.4.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libsodium=1.0.17
  - libssh2=1.9.0
  - libstdcxx-ng=8.4.0
  - llvm-openmp=10.0.0
  - llvmlite=0.33.0
  - lzstring=1.0.4
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - matplotlib-base=3.2.2
  - mistune=0.8.4
  - monotonic=1.5
  - multiprocess=0.70.10
  - multiqc=1.8
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.1
  - networkx=2.4
  - notebook=6.0.3
  - numba=0.50.1
  - numpy=1.17.5
  - openssl=1.1.1g
  - p7zip=15.09
  - packaging=20.4
  - pandas=1.0.3
  - pandoc=2.0.0.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pathos=0.2.5
  - patsy=0.5.1
  - perl=5.26.2
  - pexpect=4.8.0
  - picard=2.21.2
  - pickleshare=0.7.5
  - pip=20.0.2
  - popt=1.16
  - pox=0.2.8
  - ppft=1.6.6.1
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.5.2
  - pymdown-extensions=6.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyrsistent=0.16.0
  - pysam=0.15.4
  - pysocks=1.7.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.1
  - pyyaml=5.3.1
  - pyzmq=19.0.1
  - r-base=3.6.1
  - r-bitops=1.0_6
  - r-catools=1.17.1
  - r-chron=2.3_47
  - r-data.table=1.12.4
  - r-gdata=2.18.0
  - r-gplots=3.0.1.1
  - r-gtools=3.5.0
  - r-kernsmooth=2.23_15
  - r-lattice=0.20_35
  - r-locfit=1.5_9
  - r-markdown=1.1
  - r-mime=0.5
  - r-rcpp=0.12.17
  - readline=8.0
  - requests=2.24.0
  - ripgrep=12.0.1
  - rsync=3.1.3
  - rust=1.41.0
  - s3fs=0.4.2
  - s3transfer=0.3.3
  - samtools=1.10.0
  - scikit-learn=0.23.1
  - scipy=1.4.1
  - screed=1.0.4
  - seaborn=0.10.1
  - send2trash=1.5.0
  - seqtk=1.3
  - setuptools=49.2.0
  - simplejson=3.17.0
  - six=1.15.0
  - ska=1.0
  - snowballstemmer=2.0.0
  - sourmash=3.2.2
  - spectra=0.0.11
  - sphinx=3.1.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.32.3
  - statsmodels=0.11.1
  - subread=1.6.4
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.0.4
  - tqdm=4.45.0
  - traitlets=4.3.3
  - urllib3=1.25.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - yajl=2.1.0
  - yaml=0.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - biopython==1.77
    - fastparquet==0.4.0
    - httmock==1.3.0
    - humanfriendly==8.2
    - more-itertools==8.4.0
    - pathvalidate==2.3.0
    - pluggy==0.13.1
    - py==1.9.0
    - pytest==5.4.3
    - thrift==0.13.0
