name: nf-core CI
# This workflow is triggered on pushes and PRs to the repository.
# It runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on: [push, pull_request]

jobs:
  test:
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
      NXF_RUN: "nextflow run -resume"
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        nxf_ver: ['19.10.0', '']
        experimental: [false]
        profile_flags: ['test_fastq', 'test_download_refseq',
        'test_existing_database', 'test_bam', 'test_bam --search_noncoding',
        'test_input_is_protein', 'test_hash2kmer', 'test_diff_hash',
        'test_diff_hash --with_abundance', 'test_sourmash_search',
        'test_diff_hash_sourmash', 'test_diff_hash_is_aligned'
        ]
    steps:
      - uses: actions/checkout@v2
      - name: Install Nextflow
        run: |
          export NXF_VER=${{ matrix.nxf_ver }}
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Pull docker image
        run: |
          docker pull czbiohub/predictorthologs:dev && docker tag czbiohub/predictorthologs:dev czbiohub/predictorthologs:dev
      - name: Run pipeline with test data (single-end fastq input)
        run: |
          # TODO nf-core: You can customise CI pipeline run tests as required
          # (eg. adding multiple test runs with different parameters)
          ${NXF_RUN} ${GITHUB_WORKSPACE} -profile docker,${{ matrix.profile_flags }}
