name: nf-core CI - download refseq (allowed to fail)
# This workflow is triggered on pushes and PRs to the repository.
# This workflow runs a test of downloading the proteome database "other" from
# NCBI RefSeq but this often fails due to connection errors so this test is
# separated out from the rest of ci.yml
on: [push, pull_request]

jobs:
  refseq:
    continue-on-error: true
    timeout-minutes: 30
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
      NXF_RUN: "nextflow run -resume"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Nextflow
        run: |
          export NXF_VER=${{ matrix.nxf_ver }}
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Pull docker image
        run: |
          docker pull czbiohub/predictorthologs:dev && docker tag czbiohub/predictorthologs:dev czbiohub/predictorthologs:dev
      - name: Run pipeline with downloading refseq
        run: |
          # TODO nf-core: You can customise CI pipeline run tests as required
          # (eg. adding multiple test runs with different parameters)
          ${NXF_RUN} ${GITHUB_WORKSPACE} -profile docker,test_download_refseq
        continue-on-error: true
